; Configuration file for RepRapFirmware on Duet 3 Mini 5+ WiFi
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Wed Jan 21 2026 20:57:32 GMT+1100 (Australian Eastern Daylight Time)

; General
G90 ; absolute coordinates
M83 ; relative extruder moves
M550 P"RePrusa" ; set hostname

; Network
M552 S0 ; configure WiFi adapter
M586 P0 S1 ; configure HTTP

; Smart Drivers
M569 P0.0 S1 D3 V80 ; driver 0.0 goes forwards (X axis)
M569 P0.1 S1 D3 V80 ; driver 0.1 goes forwards (Y axis)
M569 P0.2 S0 D2 ; driver 0.2 goes backwards (Z axis)

; Motor Idle Current Reduction
M906 I30 ; set motor current idle factor
M84 S5 ; set motor current idle timeout

; Axes
M584 X0.0 Y0.1 Z0.2 ; set axis mapping
M350 X16 Y16 Z16 I1 ; configure microstepping with interpolation
M906 X800 Y800 Z800 ; set axis driver currents
M92 X100 Y100 Z860 ; configure steps per mm
M208 X-2.5:179.5 Y0:182 Z0:180 ; set minimum and maximum axis limits

M566 X900 Y900 Z12 ; set maximum instantaneous speed changes (mm/min)
M203 X6000 Y6000 Z360 ; set maximum speeds (mm/min)
M201 X500 Y500 Z20 ; set accelerations (mm/s^2)

; Kinematics
M669 K0 ; configure Cartesian kinematics

; Probes
M558 K0 P8 C"io4.in" H5 F120 T6000 ; configure unfiltered digital probe via slot #0
G31 P500 X0 Y48 Z22.5 ; set Z probe trigger value, offset and trigger height

; Endstops
M574 X1 S3 ; configure X axis endstop
M574 Y2 S3 ; configure Y axis endstop
M574 Z1 S2 ; configure Z axis endstop

; Stall detection tuning (start here, then tune)
M915 X Y S5 R0 F0 H100

; Define a “continue” button input
M950 J1 C"io5.in"          ; create input J1 on pin io0.in

; Enable uart on port 2 in device mode (S7)
M575 P2 B115200 S7
M261.2 P2 B0

; Tools
M563 P0 S"NoTool"
G10  P0 X0 Y0 Z0
G10  P0 R0

M563 P1 S"Pen"
G10  P1 X0.0 Y-5.3 Z-19.5   ; <-- replace with your measured offsets
G10  P1 R0

M563 P2 S"SingleNozzle"
G10  P2 X0.0 Y-5 Z-17.0   ; <-- replace with your measured offsets
G10  P2 R0

M563 P3 S"HennaNozzle"
G10  P3 X0.0 Y-7 Z-12.5   ; <-- replace with your measured offsets
G10  P3 R0

; Miscellaneous
T0 ; select first tool
