; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Wed Jan 21 2026 20:57:42 GMT+1100 (Australian Eastern Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home Y
G91 ; relative positioning
M913 X30 Y30 ; reduce motor current for reliable stall homing
M201.1 X300 Y300 ; gentler acceleration during homing

var maxTravel = move.axes[1].max - move.axes[1].min + 5 ; calculate how far Y can travel plus 5mm
G1 H1 Y{var.maxTravel} F3000 ; coarse home in the +Y direction
G1 Y-5 F6000 ; move back 5mm
G1 H1 Y{var.maxTravel} F2200 ; fine home in the +Y direction

M913 X100 Y100 ; restore motor currents
M201.1 X0 Y0 ; clear homing accel override
G90 ; absolute positioning

; decrease Z again
G91 ; relative positioning
G1 H2 Z-5 F6000 ; move Z relative to current position
G90 ; absolute positioning
