; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Wed Jan 21 2026 20:57:42 GMT+1100 (Australian Eastern Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home Z
var xCenter = model.move.axes[0].min + (model.move.axes[0].max - model.move.axes[0].min) / 2 - sensors.probes[0].offsets[0]
var yCenter = model.move.axes[1].min + (model.move.axes[1].max - model.move.axes[1].min) / 2 - sensors.probes[0].offsets[1]
G1 X{var.xCenter} Y{var.yCenter} F6000 ; go to bed centre
G30 ; probe the bed
